# Site settings
title: Marius Raes
description: Min personlige side
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Marius Raes
user_description: Devops trainee hos Intility i Oslo med <a href="https://www.ntnu.no/studier/bdigsec">bachelorgrad</a> fra NTNU i Gjøvik. Elsker automatisjon, skyteknologier, containere og IAC
user_title: Devops Entusiast
email: mariusraes00@gmail.com
github_username:  Marius_Raes
gplus_username:  Marius Raes

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
